# ---
# :concurrency: 1
# staging:
#   :concurrency: 1
# development:
#   :concurrency: 1
# production:
#   :concurrency: 1
:queues:
  - default
:max_retries: 1
:scheduler:
  :schedule:
    sale_worker:
      # every: '15d' 
      # at: 'Date.today.end_of_month.to_s'
      cron: '0 * * * * *'   
      # class: SaleWorker