
default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_v1_development
  username: 
  password: 

  test:
  <<: *default
  database: blog_v1_test
  username: 
  password: 

production:
  <<: *default
  database: blog_v1_production
  username: 
  password: 
