---
openapi: 3.0.1
info:
  title: 'HOME_WORK "HW89" '
  description: My first API-documentation experience
  version: v1
paths:
  "/api/v1/articles":
    post:
      summary: create article
      tags:
      - Articles
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                author_id:
                  type: integer
              required:
              - title
              - body
              - author_id
  "/api/v1/articles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show article
      tags:
      - Articles
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
