---
openapi: 3.0.1
info:
  title: 'HOME_WORK "HW89" '
  description: My first API-documentation experience
  version: v1
paths:
  "/api/v1/articles":
    get:
      summary: list articles
      tags:
      - Articles
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Find an article by title or content that contains text
      - name: status
        in: query
        schema:
          type: string
          enum:
          - unpublished
          - published
        description: 'Get articles with status: unpublished/published'
      - name: tags
        in: query
        schema:
          type: string
        description: Filter articles by tags
      - name: author
        in: query
        schema:
          type: string
        description: Get articles by name author
      - name: order
        in: query
        schema:
          type: string
        description: Sort article by asc/desc
      responses:
        '200':
          description: successful
    post:
      summary: create article
      tags:
      - Articles
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                author_id:
                  type: integer
              required:
              - title
              - body
              - author_id
  "/api/v1/articles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show article
      tags:
      - Articles
      responses:
        '200':
          description: successful
    patch:
      summary: update article
      tags:
      - Articles
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                  enum:
                  - unpublished
                  - published
              required: false
    put:
      summary: update article
      tags:
      - Articles
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                status:
                  type: string
                  enum:
                  - unpublished
                  - published
              required: false
    delete:
      summary: delete article
      tags:
      - Articles
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
